CREATE DATABASE  IF NOT EXISTS TEMPERATURAS;
USE TEMPERATURAS;

DROP TABLE IF EXISTS TEMPERATURAS;
DROP TABLE IF EXISTS FRONTERAS;
DROP TABLE IF EXISTS PAISES;

CREATE TABLE PAISES (
    ID_PAIS int NOT NULL AUTO_INCREMENT,
    NOMBRE varchar(255) NOT NULL,
    CAPITAL varchar(255) NOT NULL,
    REGION varchar(255) NOT NULL,
    SUBREGION varchar(255) NOT NULL,
    CCA2 varchar(2) NOT NULL,
    CCA3 varchar(3) NOT NULL,
    MIEMBRO_UE bit(1) NOT NULL,

    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE TEMPERATURAS (
    ID_TEMPERATURA int NOT NULL AUTO_INCREMENT,
    ID_PAIS int NOT NULL,
    TEMPERATURA float NOT NULL,
    SENSACION_TERMICA float NOT NULL,
    MINIMA float NOT NULL,
    MAXIMA float NOT NULL,
    HUMEDAD float NOT NULL,
    HORA_AMANECER time NOT NULL,
    HORA_ATARDECER time NOT NULL,

    PRIMARY KEY (ID_TEMPERATURA),
    KEY FK_PAIS_TEMPERATURA_IDX (ID_PAIS),
    CONSTRAINT FK_PAIS_TEMPERATURA FOREIGN KEY (ID_PAIS) REFERENCES PAISES (ID_PAIS)
);

CREATE TABLE FRONTERAS (
    ID_FRONTERAS int AUTO_INCREMENT,
    ID_PAIS int NOT NULL,
    CCA3_FRONTERA varchar(3) NOT NULL,

    PRIMARY KEY (ID_FRONTERAS),
    KEY FK_FRONTERA_PAIS_IDX (ID_PAIS),
    CONSTRAINT FK_FRONTERA_PAIS_IDX FOREIGN KEY (ID_PAIS) REFERENCES PAISES (ID_PAIS)
);
